name: scanner
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5+9
  tflite_flutter: ^0.10.4
  image: ^4.0.17
  path_provider: ^2.0.15
  image_picker: ^1.0.0
  exif: ^3.1.4
  provider: ^6.1.2
  go_router: ^14.1.4
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^2.0.2
  convex_bottom_bar: ^3.2.0
  intl: ^0.19.0
  pusher_channels_flutter: ^2.2.1
  flutter_pytorch: ^1.0.1
  shared_preferences: ^2.2.3
  file_picker: ^8.0.6
  syncfusion_flutter_charts: ^27.1.50

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
